config/routes.rb
Rails.application.routes.draw do
	root"users#index"
	resources :users

	root"pages#index"
		get "page-top-secrete", to: "pages#index"

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
 before_save { self.email = email.downcase }
  validates :name, presence: true, length: { maximum: 50 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, length: { maximum: 255 },
                    format: { with: VALID_EMAIL_REGEX },
                    uniqueness: { case_sensitive: false }
  has_secure_password
  validates :password, presence: true, length: { minimum: 6 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

	def index

	end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(params_user)
      if @user.save
        redirect_to @user
      else
        render "new"
      end
  end

  def show
    @user = User.find(params[:id])
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update(params_user)
      redirect_to users_path
    else
      render "new"
    end
  end

  def destroy
    @user = User.find(params[:id])
    @user.destroy
    redirect_to users_path
  end

  private
  def params_user
    params.permit(:name, :email)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Secret</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/pages/index.html.erb
<h1>Bienvenu sur la page top secrete!</h1>

app/views/users/_form.html.erb
	<%= label_tag 'name', "Nom de l'utilsateur" %> 
	<%= text_field_tag 'name' %> 

	<%= label_tag 'email', 'Email' %> 
	<%= text_field_tag 'email' %>

	<%= label_tag 'password', 'Mot de passe' %> 
	<%= text_field_tag 'password' %>

app/views/users/edit.html.erb
<h1>Editer l'utilisateur</h1>
<%= form_tag (users_path) do %>   
  <%= render 'form' %>
	<%= submit_tag "Editer l'utilisateur"%> 
<% end %>

app/views/users/index.html.erb
<h1>Listes des utilisateurs</h1>

<%= link_to "Page top secrete", page_top_secrete_path %>

app/views/users/new.html.erb
<h1>Créer un nouvel utilisateur</h1>

<%= form_tag (users_path) do %>   
  <%= render 'form' %>
	<%= submit_tag "Créer nouvel utilisateur"%> 
<% end %>

app/views/users/show.html.erb
<h1>Profil utilisateur</h1>

<%= @user.name %>
<%= @user.email %>

<%= link_to "Editer l'utilisateur", edit_user_path %>
<%= link_to "Supprimer l'utilisateur", user_path,
			method: :delete,
			data: {confirm: "Are you sure"} %>